version: "3"
services:
  mongodb:
    image : flqw/docker-mongo-local-replicaset
    container_name: mongodb
    restart: always
    env_file:
      - ./.server-env
    ports:
      - 27001:27001
      - 27002:27002
      - 27003:27003