version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=apitect
      - POSTGRES_PASSWORD=apitect42
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
#     - ./database/pg:/var/lib/postgresql/data
      - ./database/install_db.sql:/docker-entrypoint-initdb.d/create_tables.sql